name: CI

on:
  push:
  workflow_dispatch: 
    inputs:
      progressStatus:
        description: 'This defines how the workflow will run'
        required: true
        type: boolean  

concurrency: 
  group: development-env
  cancel-in-progress: ${{ github.event.inputs.progressStatus }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
